# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /var/lib/snapd/snap/cmake/852/bin/cmake

# The command to remove a file.
RM = /var/lib/snapd/snap/cmake/852/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/carlos-sweb/Escritorio/css-utility-minify

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/carlos-sweb/Escritorio/css-utility-minify

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/var/lib/snapd/snap/cmake/852/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/var/lib/snapd/snap/cmake/852/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/carlos-sweb/Escritorio/css-utility-minify/CMakeFiles /home/carlos-sweb/Escritorio/css-utility-minify//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/carlos-sweb/Escritorio/css-utility-minify/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named css-utility-minify

# Build rule for target.
css-utility-minify: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 css-utility-minify
.PHONY : css-utility-minify

# fast build rule for target.
css-utility-minify/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/css-utility-minify.dir/build.make CMakeFiles/css-utility-minify.dir/build
.PHONY : css-utility-minify/fast

css-utility-minify.o: css-utility-minify.c.o

.PHONY : css-utility-minify.o

# target to build an object file
css-utility-minify.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/css-utility-minify.dir/build.make CMakeFiles/css-utility-minify.dir/css-utility-minify.c.o
.PHONY : css-utility-minify.c.o

css-utility-minify.i: css-utility-minify.c.i

.PHONY : css-utility-minify.i

# target to preprocess a source file
css-utility-minify.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/css-utility-minify.dir/build.make CMakeFiles/css-utility-minify.dir/css-utility-minify.c.i
.PHONY : css-utility-minify.c.i

css-utility-minify.s: css-utility-minify.c.s

.PHONY : css-utility-minify.s

# target to generate assembly for a file
css-utility-minify.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/css-utility-minify.dir/build.make CMakeFiles/css-utility-minify.dir/css-utility-minify.c.s
.PHONY : css-utility-minify.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... css-utility-minify"
	@echo "... css-utility-minify.o"
	@echo "... css-utility-minify.i"
	@echo "... css-utility-minify.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

